#include <array>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <random>
#include <stdexcept>
#include <string>

#include "Vorder_book_cpp_wrapper.h"  // C++ class generated by Verilator from the RTL wrapper.
#include "verilated.h"                 // Verilator simulation clock/time support.

#include "market/order_book.hpp"       // The trusted C++ reference order book.

namespace {

using market_engine::market::ApplyResult;
using market_engine::market::BookError;
using market_engine::market::BookSnapshot;
using market_engine::market::EventType;
using market_engine::market::MarketEvent;
using market_engine::market::OrderBook;
using market_engine::market::PriceLevel;
using market_engine::market::Side;

// Run a long deterministic comparison. A mismatch at any event fails the test.
constexpr std::size_t kEvents = 1'000'000;
// A single order-book transaction must always complete within this many RTL cycles.
constexpr std::size_t kCycleLimit = 32;

// Advance the Verilated design through one full clock cycle: evaluate at clock-low,
// advance simulated time, evaluate at clock-high, then advance time again.
void tick(VerilatedContext& context, Vorder_book_cpp_wrapper& dut) {
    dut.clk = 0;
    dut.eval();
    context.timeInc(5);
    dut.clk = 1;
    dut.eval();
    context.timeInc(5);
}

// Put the RTL into its defined empty-book state. The C++ reference OrderBook starts
// empty automatically, so both implementations begin from the same state.
void reset(VerilatedContext& context, Vorder_book_cpp_wrapper& dut) {
    dut.rst_n = 0;
    dut.in_valid = 0;
    dut.timestamp_ns = 0;
    dut.event_type = 0;
    dut.side = 0;
    dut.price_ticks = 0;
    dut.quantity = 0;
    tick(context, dut);
    tick(context, dut);
    dut.rst_n = 1;
    tick(context, dut);
    if (!dut.in_ready) throw std::runtime_error("RTL did not become ready after reset");
}

// Drive one MarketEvent through the RTL valid/ready handshake, then wait for its
// one-cycle event_done response. A timeout catches a stalled RTL state machine.
void submit(VerilatedContext& context, Vorder_book_cpp_wrapper& dut, const MarketEvent& event) {
    while (!dut.in_ready) tick(context, dut);
    dut.timestamp_ns = event.timestamp_ns;
    dut.event_type = static_cast<std::uint8_t>(event.type);
    dut.side = static_cast<std::uint8_t>(event.side);
    dut.price_ticks = static_cast<std::uint32_t>(event.price_ticks);
    dut.quantity = event.quantity;
    dut.in_valid = 1;
    tick(context, dut);
    dut.in_valid = 0;

    for (std::size_t cycles = 0; cycles < kCycleLimit; ++cycles) {
        tick(context, dut);
        if (dut.event_done) return;
    }
    throw std::runtime_error("RTL event timed out");
}

// Read one flattened 64-bit snapshot output from the wrapper. Verilator exposes
// those outputs as named C++ fields, so this switch selects the requested level.
std::uint64_t rtl_level(const Vorder_book_cpp_wrapper& dut, const bool bid, const std::size_t index) {
    if (bid) {
        switch (index) {
            case 0: return dut.bid_level0; case 1: return dut.bid_level1;
            case 2: return dut.bid_level2; case 3: return dut.bid_level3;
            case 4: return dut.bid_level4; case 5: return dut.bid_level5;
            case 6: return dut.bid_level6; case 7: return dut.bid_level7;
            case 8: return dut.bid_level8; case 9: return dut.bid_level9;
            default: break;
        }
    } else {
        switch (index) {
            case 0: return dut.ask_level0; case 1: return dut.ask_level1;
            case 2: return dut.ask_level2; case 3: return dut.ask_level3;
            case 4: return dut.ask_level4; case 5: return dut.ask_level5;
            case 6: return dut.ask_level6; case 7: return dut.ask_level7;
            case 8: return dut.ask_level8; case 9: return dut.ask_level9;
            default: break;
        }
    }
    throw std::out_of_range("invalid RTL snapshot index");
}

// Split one packed RTL price level into price and quantity, then compare it with
// the corresponding C++ reference level. The first mismatch stops the long test.
void compare_level(const PriceLevel& expected, const std::uint64_t actual, const std::size_t event_index,
                   const char* side, const std::size_t level) {
    const auto actual_price = static_cast<std::int32_t>(actual >> 32U);
    const auto actual_quantity = static_cast<std::uint32_t>(actual);
    if (expected.price_ticks != actual_price || expected.quantity != actual_quantity) {
        throw std::runtime_error("book mismatch at event " + std::to_string(event_index) + " " + side +
                                 " level " + std::to_string(level));
    }
}

// Compare every externally visible result from one event: error code, two flow
// deltas, all ten bid levels, and all ten ask levels.
void compare(const Vorder_book_cpp_wrapper& dut, const BookSnapshot& expected, const ApplyResult& result,
             const std::size_t event_index) {
    if (static_cast<std::uint8_t>(result.error) != dut.event_error || result.order_flow_delta != dut.order_flow_delta ||
        result.trade_flow_delta != dut.trade_flow_delta) {
        throw std::runtime_error("result mismatch at event " + std::to_string(event_index));
    }
    for (std::size_t level = 0; level < 10; ++level) {
        compare_level(expected.bids[level], rtl_level(dut, true, level), event_index, "bid", level);
        compare_level(expected.asks[level], rtl_level(dut, false, level), event_index, "ask", level);
    }
}

// Pick one currently populated level from the requested side. Returning nullptr
// means that side is empty, so the generator must create an Add event instead.
const PriceLevel* choose_level(const BookSnapshot& book, const Side side, std::mt19937& random) {
    const auto& levels = side == Side::Bid ? book.bids : book.asks;
    std::size_t size = 0;
    while (size < levels.size() && levels[size].quantity != 0U) ++size;
    if (size == 0U) return nullptr;
    return &levels[std::uniform_int_distribution<std::size_t>(0U, size - 1U)(random)];
}

// Generate one valid, deterministic event. It uses the C++ book snapshot only to
// select real prices for Update/Cancel/Trade; both C++ and RTL still receive the
// exact same resulting event and are independently compared afterwards.
MarketEvent next_event(const BookSnapshot& book, const std::size_t index, std::mt19937& random) {
    const Side side = std::uniform_int_distribution<int>(0, 1)(random) == 0 ? Side::Bid : Side::Ask;
    const PriceLevel* existing = choose_level(book, side, random);
    const int choice = existing ? std::uniform_int_distribution<int>(0, 99)(random) : 0;
    const EventType type = !existing || choice < 45 ? EventType::Add
                         : choice < 60 ? EventType::Update
                         : choice < 80 ? EventType::Cancel : EventType::Trade;
    const std::int32_t price = type == EventType::Add
        ? std::uniform_int_distribution<std::int32_t>(side == Side::Bid ? 9991 : 10002,
                                                      side == Side::Bid ? 10000 : 10011)(random)
        : existing->price_ticks;
    const std::uint32_t quantity = type == EventType::Update
        ? std::uniform_int_distribution<std::uint32_t>(0U, 1000U)(random)
        : (type == EventType::Add ? std::uniform_int_distribution<std::uint32_t>(1U, 1000U)(random)
                                  : std::uniform_int_distribution<std::uint32_t>(1U, existing->quantity + 500U)(random));
    return {.timestamp_ns = 1'000U + index * 10U, .type = type, .side = side, .price_ticks = price, .quantity = quantity};
}

}  // namespace

int main(int argc, char** argv) {
    // `dut` is the Verilated RTL implementation. `reference` is the existing C++
    // correctness oracle. The fixed seed makes this one-million-event replay repeatable.
    VerilatedContext context;
    context.commandArgs(argc, argv);
    Vorder_book_cpp_wrapper dut{&context};
    OrderBook reference;
    std::mt19937 random{42U};

    try {
        reset(context, dut);
        for (std::size_t index = 0; index < kEvents; ++index) {
            // Build one event, apply it to both models, and compare all observable
            // state immediately so the reported failure index is useful for debugging.
            const MarketEvent event = next_event(reference.snapshot(), index, random);
            const ApplyResult expected = reference.apply(event);
            submit(context, dut, event);
            compare(dut, reference.snapshot(), expected, index);
        }
        std::cout << "C++/RTL order-book differential test passed: " << kEvents << " events.\n";
    } catch (const std::exception& error) {
        // Give Verilator a chance to perform its normal simulation shutdown before
        // reporting the mismatch or timeout to the test runner.
        std::cerr << "C++/RTL order-book differential test failed: " << error.what() << '\n';
        dut.final();
        return 1;
    }
    dut.final();
    return 0;
}
